# Generated by Django 3.1.7 on 2021-03-06 21:21

import api.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=120)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=api.models.Status)),
            ],
        ),
    ]
